require "user.options"
require "user.keymaps"
require "user.plugins"

require "user.plugin.lualine"
require "user.plugin.tree"
require "user.plugin.devicons"
require "user.plugin.telescope"
require "user.plugin.toggleterm"
require "user.plugin.bufferline"
require "user.plugin.gitsigns"
require "user.plugin.indent-blankline"
require "user.plugin.comment"
require "user.plugin.cmp"
require "user.plugin.lsp-installer"
require "user.plugin.lspconfig"
require "user.plugin.lspkind"
require "user.plugin.lsp-saga"
require "user.plugin.treesitter"
require "user.plugin.autopairs"
require "user.plugin.ts-autotag"
require "user.plugin.luasnip"
require "user.plugin.prettier"
require "user.plugin.null-ls"
require "user.plugin.colorscheme"
-- require "user.plug.which-key"
